name: Build

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch: 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Install Dependencies
        run: npm build