name: Build

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch: 

jobs:
  build:
    name: App Build
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: npm install

runs-on:
  using: 'node19'
  main: 'src/index.js'