name: build.js

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20,22,00 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-repositpry
        uses: actions/checkout@v2

      - name: run-nodejs-file
        run: npm install && node './src/index.js'

      - name: check-for-changes
        run: git diff-index --quiet HEAD --

      - name: commit-and-push-changes
        if: steps.check-for-changes.outputs.exit_code == 1
        run: |
          git config --local user.email "jeferson.i.silva@gmail.com"
          git config --local user.name "Jeferson Silva"

          git add .
          git commit -m "Auto commit by GitHub Action at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push