# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build.js

on:
  schedule:
    - cron:  '* 6 * * *'
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install && node './src/index.js'
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Jefeferson Silva
        author_email: jeferson.i.silva@gmail.com
        committer_name: Jefeferson Silva
        committer_email: jeferson.i.silva@gmail.com
        message: 'Data generated via schedule'