# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build.js

on:
  schedule:
    - cron: '6 6 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run JavaScript file
        run: npm install && node './src/index.js'

      - name: Commit and push changes
        run: |
          git config --local user.email "jeferson.i.silva@gmail.com"
          git config --local user.name "Jeferson Silva"

          git add .
          git commit -m "Auto commit by GitHub Action at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push