name: build.js

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20,22,00 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run JavaScript file
        run: npm install && node './api/index.js'

      - name: Check changes
        id: check_changes
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "::set-output name=has_changes::true"
          else
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "jeferson.i.silva@gmail.com"
          git config --local user.name "Jeferson Silva"

          git add .
          git commit -m "Auto commit by GitHub Action at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push